### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by imelekhov** [ducha-aiki/mods-light-zmq#1]
Hi,
There is an issue in the compilation process. To be more specific, the problem is in line 38 of `imagerepresentation.cpp` file. The interface function `connect` expects to have `const char*` as an input but `string` variable is provided. So, changing the original version to `socket.connect(par.port.c_str());` should fix the problem.

**Comment by ducha-aiki** [comment]
Hi,
That`s weird - works for me. Probably different version of some lib. Could you please tell me the version, so I can test?

**Comment by imelekhov** [comment]
I see! It is related to `libzmq` library which is quite old on my machine (v 4.0.4). In this particular version, there is only one interface function `inline void connect(const char *addr)` handling a char array and not a string.
