### ISSUE TITLE
poor performance

### ISSUE THREAD

**Issue by Nestart** [ducha-aiki/mods-light-zmq#4]
when I use it to match below images,it has poor performance ,can you give me some suggestions?

![3](https://user-images.githubusercontent.com/34918269/82641470-f45f1980-9c3e-11ea-96b4-94d7617004f9.jpg)
![30](https://user-images.githubusercontent.com/34918269/82641529-0fca2480-9c3f-11ea-83da-001f677b1537.jpg)

**Comment by ducha-aiki** [comment]
No. Images are super low quality, method is not supposed to work there :)
